sudo: false
language: node_js
branches:
  only:
  - master
cache: yarn
stages:
- name: test
  if: branch = master AND type = pull_request
jobs:
  include:
  - stage: test
    script:
    - yarn run lint
    - yarn build
    - yarn run test:ci
    node_js:
    - '10'
